import React from 'react';

const ConditionUse = () => {
  return (
    <div className="flex justify-center items-center min-h-screen mt-40 p-4">
      <div className="bg-white max-w-2xl rounded-lg shadow-lg p-8">
        <h1 className="text-3xl font-bold text-gray-800 mb-4">General Privacy Policy</h1>
        <p className="text-gray-500 mb-6">
            Last updated: November 13, 2024
          <br />
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mb-3">1. Interpretation and Definitions</h2>
        <h3 className="text-lg font-semibold text-gray-800 mb-2">Interpretation</h3>
        <p className="text-gray-500 mb-4">
        Words whose first letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning whether they appear in the singular or the plural.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mb-2">Definitions</h3>
        <p className="text-gray-500">
        For the purposes of this Privacy Policy:
          <br />
          - Account means a unique account created for you to access our Service or parts of our Service.
          <br />
          - Affiliate means an entity that controls, is controlled by or is under common control with a party.
          <br />
          - Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Docxtalk.
          <br />
          - Cookies are small files placed on your computer, mobile device or other device by a website.
          <br />
          - Country means: Cameroun
          <br />
          - Device means any device that can access the Service.
          <br />
          - Personal Data means any information relating to an identified or identifiable individual. - Service means the Website.
          <br />
          - Service Provider means any natural or legal person who processes data on behalf of the Company.
          <br />
          - Usage Data means data collected automatically, generated by the use of the Service or from the Service infrastructure itself.
          <br />
          - Website means Docxtalk, accessible from docx-talk.com
          <br />
          - You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">2. Collection and Use of your Personal Data</h2>
        <p className="text-gray-500 mt-4">
            Types of Data Collected
          <br />
          
        </p>
        <h4 className="text-lg font-semibold text-gray-600 mt-2">Personal Data</h4>
        <p className='text-gray-500 mt-4'>
        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:
            <br/>
            - E-mail address
            <br/>
            - First and last name
            <br/>
            - Usage data
        </p>
        <h4 className="text-lg font-semibold text-gray-600 mt-2">Usage Data</h4>
        <p className='text-gray-500 mt-4'>
            Usage data is collected automatically when using the service
         <br/>
         <br/>
         Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
         <br/>
         <br/>
         When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
         <br/>
         <br/>
         We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device. Tracking Technologies and Cookies.
         <br/>
         <br/>
         We use cookies and similar tracking technologies to track the activity on our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service. The technologies we use may include:
         <br/>
         <br/>
         Cookies or Browser Cookies. A cookie is a small file that is placed on your device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. Unless you have adjusted your browser setting so that it will refuse cookies, our Service may use cookies.
         <br/>
         <br/>
         Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
         <br/>
         <br/>
         Cookies may be either "persistent" cookies or "session" cookies. Persistent cookies remain on your personal computer or mobile device when you log out, while session cookies are deleted as soon as you close your web browser. Learn more about cookies on the Free Privacy Policy website article. We use both session and persistent cookies for the purposes set out below:
         <br/>
         <br/>
         Necessary / Essential Cookies
         <br/>
         Type: Session cookies
         <br/>
         Administered by: Us
         <br/>
         Purpose: These cookies are essential to provide you with services available through the Website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these cookies, services you have asked for cannot be provided, and we only use these cookies to provide you with those services.
         <br/>
         <br/>
         Cookies Policy / Acceptance Notice
         <br/>
         Type: Persistent Cookies
         <br/>
         Administered by: Us
         <br/>
         Purpose: These cookies identify whether users have accepted the use of cookies on the website.
         <br/>
         <br/>
         Functionality Cookies
         <br/>
         Type: Persistent Cookies
         <br/>
         Administered by: Us
         <br/>
         Purpose: These cookies allow us to remember choices you make when you use the Website, such as remembering your login details or your language preference when translating your documents. The purpose of these cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the Website. For more information about the cookies we use and your cookie choices, please see our Cookie Policy or the cookies section of our Privacy Policy.
        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">3. Google Privacy Policy and Data Usage</h2>
        <p className="text-gray-500 mt-4">
            Adspell's use and transfer of information received through <a href='https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes' className='text-black underline'>Google APIs adheres to Google's API Services Policy on User Data</a> , including Limited Use requirements. This practice is clearly defined and easily accessible to all our users to ensure transparency in our processes.
          <br />
          <br />
          The application is committed to respecting this policy and ensures the protection and confidentiality of personal data obtained from Google APIs according to restricted and sensitive scopes. No transfer of this data to another application is made without strictly adhering to the guidelines dictated by Google.
          <br />
          <br />
          <h2 className="text-xl font-semibold text-gray-800 mt-3">4. Use of your Personal Data</h2>
        </p>
        <p className="text-gray-500 mt-4">
            The Company may use personal data for the following purposes:
            <br />
            <br />
            - To provide and maintain our service
            <br />
            - To manage the sending of your documents directly to the recipient
            <br />
            - For the execution and generation of your documents
            <br />
            - To contact you
            <br />
            - To provide you with news, special offers and general information
            <br />
            - To manage your requests
            <br />
            - For business transfers
            <br />
            - other purposes
            <br />
            <br />

        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">5. Retention of your Personal Data</h2>
        <p className="text-gray-500 mt-2">
            The Company will retain your personal data only for as long as necessary for the purposes set out in this Privacy Policy. We will retain and use your personal data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
            <br />
            <br />
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods of time in the case of for example, automated sending of generated documents to recipients or process automation.
        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">6. Transfer of your Personal Data</h2>
        <p className="text-gray-500 mt-2">
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
            <br />
            <br />
            Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
            <br />
            <br />
            The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">7. Deletion of your Personal Data</h2>
        <p className="text-gray-500 mt-2">
            You have the right to delete or request our assistance in deleting the personal data we have collected about you.
         <br />
         <br />
            Our Service may allow you to delete certain information about you from the Service.
         <br />
         <br />
         You may update, modify or delete your information at any time by logging into your account if you have one, and visiting the account settings section which allows you to manage your personal information. You may also contact us to request access to, correct or delete any personal information you have provided to us.
         <br />
         Please note, however, that we may be required to retain certain information where we have a legal obligation or legal basis to do so.
        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">8. Disclosure of your Personal Data</h2>
        <p className="text-gray-500 mt-2">
            Business transactions
         <br />
         <br />
         If the Company is involved in a merger, acquisition or asset sale, your personal data may be transferred. We will notify you before your personal data is transferred and becomes subject to a different privacy policy.
         <br />
         <br />
         Law enforcement
         <br />
         <br />
         Under certain circumstances, the Company may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
         <br />
         <br />
         Other legal requirements
         <br />
         The Company may disclose your personal data in the good faith belief that such action is necessary to:
         <br />
         <br />
            Comply with a legal obligation
            Protect and defend the rights or property of the Company
            Prevent or investigate possible wrongdoing in connection with the Service
            Protect the personal safety of users of the Service or the public
            Protect against legal liability

        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">9. Security of your Personal Data</h2>
        <p className="text-gray-500 mt-2">
        The security of your Personal Data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">10. Links to Other Websites</h2>
        <p className="text-gray-500 mt-2">
            Our Service may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
            <br />
            <br />
            We have no control over and assume no responsibility for the content, privacy policies, or practices of any third party sites or services.
        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">11. Changes to this Privacy Policy</h2>
        <p className="text-gray-500 mt-2">
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            <br />
            <br />
            We will let You know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy.
            <br/>
            <br/>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>
        <h2 className="text-xl font-semibold text-gray-800 mt-3">12. Contact Us</h2>
        <p className="text-gray-500 mt-2">
        If you have any questions about this privacy policy, you can contact us: - By email: contact@docxtalk.com - By visiting this page on our website: docx-talk.com/TOS
        </p>
      </div>
    </div>
  );
};

export default ConditionUse;
